name: Local Test Execution

on:
  
  push:
    branches: [jay]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  pull-requests: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  regression:
    name: Run Automation Regression on Local Machine
    runs-on: self-hosted
    environment:
      name: github-pages

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Allure
        run: npm install -D allure-playwright


      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run regression tests
        id: run_tests
        run: npm run test:ci:smoke
        continue-on-error: true

      - name: Upload Playwright report as Pages artifact
        if: always()
        uses: actions/upload-pages-artifact@v4
        with:
          path: playwright-report

      - name: Upload Playwright report as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

      - name: Upload Allure results (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/

      - name: Deploy Playwright report to GitHub Pages
        if: always()
        id: deployment
        uses: actions/deploy-pages@v4
        continue-on-error: true
          
      - name: Fail if test cases failed
        if: steps.run_tests.outcome == 'failure'
        run: |
                echo "Tests failed ‚ùå"
                exit 1  
     
