name: PR Smoke Suite

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, develop]
 
permissions:
  contents: read
  pull-requests: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  regression:
    name: Run Automation Regression + PR Comment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Allure
        run: npm install -D allure-playwright


      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run regression tests
        id: run_tests
        run: npm run test:ci:demo
        continue-on-error: true

      - name: Upload Playwright report as Pages artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

      - name: Upload Allure results (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/
          
     # -------------------------
      # PR TEST SUMMARY
      #üìÑ **HTML Report:**  
      #      üëâ https://jay-ut.github.io/utis-playwright-framework/
      # -------------------------
      - name: Publish test summary to PR
        if: always() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');

            if (!fs.existsSync('playwright-results.json')) {
              console.log('No Playwright JSON found');
              return;
            }

            const results = JSON.parse(
              fs.readFileSync('playwright-results.json', 'utf8')
            );

            const stats = results.stats || {};

            const passed = stats.expected ?? 0;
            const failed = stats.unexpected ?? 0;
            const skipped = stats.skipped ?? 0;
            const flaky = stats.flaky ?? 0;

            const runUrl = `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}#artifacts`;
            const body = `
            üß™ **Playwright Test Summary**

            ‚úÖ Passed: **${passed}**  
            ‚ùå Failed: **${failed}**  
            ‚è≠Ô∏è Skipped: **${skipped}**  
            ‚ö†Ô∏è Flaky: **${flaky}**

            üìÑ **Report Artifact:**  
            üëâ ${runUrl}

            
            `;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body
            });

            name: PR Smoke Suite

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, develop]
 
permissions:
  contents: read
  pull-requests: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  regression:
    name: Run Automation Regression
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Allure
        run: npm install -D allure-playwright


      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run regression tests
        id: run_tests
        run: npm run test:ci:regression
        continue-on-error: true

      - name: Upload Playwright report as Pages artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

      - name: Upload Allure results (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/
          
     # -------------------------
      # PR TEST SUMMARY
      #üìÑ **HTML Report:**  
      #      üëâ https://jay-ut.github.io/utis-playwright-framework/
      # -------------------------
      - name: Publish test summary to PR
        if: always() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');

            if (!fs.existsSync('playwright-results.json')) {
              console.log('No Playwright JSON found');
              return;
            }

            const results = JSON.parse(
              fs.readFileSync('playwright-results.json', 'utf8')
            );

            const stats = results.stats || {};

            const passed = stats.expected ?? 0;
            const failed = stats.unexpected ?? 0;
            const skipped = stats.skipped ?? 0;
            const flaky = stats.flaky ?? 0;

            const runUrl = `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}#artifacts`;
            const body = `
            üß™ **Playwright Test Summary**

            ‚úÖ Passed: **${passed}**  
            ‚ùå Failed: **${failed}**  
            ‚è≠Ô∏è Skipped: **${skipped}**  
            ‚ö†Ô∏è Flaky: **${flaky}**

            üìÑ **Report Artifact:**  
            üëâ ${runUrl}

            
            `;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body
            });

      - name: Fail if test cases failed
        if: steps.run_tests.outcome == 'failure'
        run: |
                echo "Tests failed ‚ùå"
                exit 1  

