name: Regression Tests Suite

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - Shaarif

jobs:
  regression:
    name: Run Automation Regression
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps
     
      # Cache Playwright Browsers
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}  

      - name: Run regression tests
        run: npm run report:smoke

      - name: Upload Playwright HTML reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-reports
          path: reports/


      # - name: Upload Playwright report
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: playwright-report
      #     path: playwright-report/

      - name: Upload Latest Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-latest-report
          path: reports/latest

      - name: Upload Allure Archived Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-archive-reports
          path: reports/archive    

      # - name: Upload Allure results
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: allure-results
      #     path: allure-results/

      # - name: Generate Allure report with timestamp
      #   if: always()
      #   run: |
      #     TIME=$(date +'%Y%m%d_%H%M%S')
      #     npx allure generate allure-results --clean --single-file -o allure-report-$TIME
      #     echo "REPORT_FOLDER=allure-report-$TIME" >> $GITHUB_ENV

      # - name: Upload Allure HTML report
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ${{ env.REPORT_FOLDER }}
      #     path: ${{ env.REPORT_FOLDER }}